blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.blog_index, name="index"),
    path("<int:pk>/", views.blog_detail, name="detail"),
    path("<category>/", views.blog_category, name="category"),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("projects/", include("projects.urls")),
    path("blog/", include("blog.urls")),
    path("todo/", include("todo_list.urls")),
]

projects/urls.py
from django.urls import path, include
from . import views

app_name = "projects"

urlpatterns = [
    path("", views.project_index, name = "index"),
    path("<int:pk>/", views.project_detail, name = "project_detail"),
]

todo_list/urls.py
from django.urls import path
from . import views

app_name = "todo_list"

urlpatterns = [
    path("", views.main_page, name = "main_page"),
    path("<int:pk>/", views.task_details, name = "task_details"),
    path("delete/<int:pk>/", views.delete_task, name = "delete_task"),
]

blog/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=20)


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    #This field links the Post and Category models and creates a relationship between the two tables.
    categories = models.ManyToManyField('Category', related_name='posts')

class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    #One post can have many comments (one-to-many) / models.CASCADE to delete all comments related to a post when the post is deleted
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.FilePathField(path="/img")
    url = models.URLField

todo_list/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    end_date = models.DateField()

blog/forms.py
from django import forms

class CommentForm(forms.Form):
    author = forms.CharField(
        #Lenght same as Comment model max length
        max_length=60,
        #Text input widget
        widget=forms.TextInput(
            attrs={
            #css class
            "class": "form-control",
            #placeholder text
            "placeholder": "Your Name"
            }
        )
    )
    #Text area widget
    body = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Leave a comment!"
            }
        )
    )

todo_list/forms.py
from django import forms

class NewTaskForm(forms.Form):
    title = forms.CharField(
        max_length = 100,
        widget = forms.TextInput(
            attrs = {
                "class": "form-control",
                "placeholder": "Task Title"
            }
        )
    )
    
    description = forms.CharField(
        widget = forms.Textarea(
            attrs = {
                "class": "form-control",
                "placeholder": "Task Description"
            }
        )
    )

    end_date = forms.DateField(
        widget = forms.DateInput(
            attrs = {
                "placeholder" : "dd-mm-yy"
            }
        ),
        input_formats = (
                '%Y-%d-%m', '%d/%m/%Y', '%d/%m/%y', # '2006-25-10', '25/10/2006', '25/10/06' 
                '%d-%m-%Y','%d-%m-%y',              # '25-10-2006', '25-10-06'
                '%d %b %Y', '%d %b, %Y',            # '25 Oct 2006', '25 Oct, 2006'               
                '%d %B %Y', '%d %B, %Y',            # '25 October 2006', '25 October, 2006'
        )
    )

blog/views.py
from django.shortcuts import render
from blog.models import Post, Comment, Category
from blog.forms import CommentForm

# Create your views here.
def blog_index(request):
    #Obtain Queryset containing all the posts in the database.
    posts = Post.objects.all().order_by('-created_on')
    context = {
        "posts": posts,
    }
    return render(request, "blog_index.html", context)

def blog_category(request, category):
    posts = Post.objects.filter(
        categories__name__contains=category
    ).order_by(

        '-created_on'
    )
    context = {
        "category": category,
        "posts": posts
    }
    return render(request, "blog_category.html", context)

def blog_detail(request, pk):
    post = Post.objects.get(pk=pk)
    
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data["author"],
                body=form.cleaned_data["body"],
                post=post
            )
            comment.save()

    comments = Comment.objects.filter(post=post)
    context = {
        "post": post,
        "comments": comments,
        "form": form,
    }
    return render(request, "blog_detail.html", context)

projects/views.py
from django.shortcuts import render
from projects.models import Project
# Create your views here.


def project_index(request):
    projects = Project.objects.all()
    context = {
        'projects': projects
    }
    return render(request, 'project_index.html', context)

def project_detail(request, pk):
    project = Project.objects.get(pk = pk)
    context = {
        'project': project,
    }
    return render(request, 'project_detail.html', context)

todo_list/views.py
from django.shortcuts import render, redirect
from todo_list.models import Task
from todo_list.forms import NewTaskForm
from datetime import date
# Create your views here.


def main_page(request):
    if request.method == 'POST':
        print(request.POST)
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = Task(
                title = form.cleaned_data['title'],
                description = form.cleaned_data['description'],
                end_date = form.cleaned_data['end_date']
            )
            task.save()
    else:
        form = NewTaskForm()
    tasks = Task.objects.all()
    return render(request, 'main_page.html', {'form': form, 'tasks': tasks})

def task_details(request, pk):
    task = Task.objects.filter(pk = pk)
    if request.method == 'POST':
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task.update(title = form.cleaned_data['title'])
            task.update(description = form.cleaned_data['description'])
            task.update(end_date = form.cleaned_data['end_date'])
            return redirect('todo_list:main_page')
    else:
        task = task.first()
        form = NewTaskForm(initial = {
            'title': task.title,
            'description': task.description,
            'end_date': task.end_date
        })
    return render(request, 'task_details.html', {'form': form, 'task': task})

def delete_task(request, pk):
    if request.method == 'POST':
        Task.objects.filter(pk = pk).delete()
        return redirect('todo_list:main_page')

blog/templates/blog_category.html
{% extends "base.html" %}
{% block page_content %}

<div class="col-md-8 offset-md-2">
    <h1>{{ category | title }}</h1>
    <hr>
    {% for post in posts %}
        <h2><a href="{% url 'blog:detail' post.pk%}">{{ post.title }}</a></h2>
        <small>
            {{ post.created_on.date }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
            <a href="{% url 'blog:category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
            {% endfor %}
        </small>
        <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog_detail.html
{% extends "base.html" %}
{% block page_content %}
<div class="col-md-8 offset-md-2">
    <h1>{{ post.title }}</h1>
    <small>
        {{ post.created_on.date }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'blog:category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | linebreaks }}</p>
    <h3>Leave a comment:</h3>
    <form action="/blog/{{ post.pk }}/" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.author }}
        </div>
        <div class="form-group">
            {{ form.body }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <h3>Comments:</h3>
    {% for comment in comments %}
    <p>
        On {{comment.created_on.date }}&nbsp;
        <b>{{ comment.author }}</b> wrote:
    </p>
    <p>{{ comment.body }}</p>
    <hr>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog_index.html
{% extends "base.html" %}
{% block page_content %}

<div class="col-md-8 offset-md-2">
    <h1>Blog Index</h1>
    <hr>
    {% for post in posts %}
    <h2><a href="{% url 'blog:detail' post.pk%}">{{ post.title }}</a></h2>
    <small>
        {{ post.created_on.date }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'blog:category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>
{% endblock %}

personal_portfolio/templates/base.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

{% block navbar%}
{% endblock navbar %}

{% block page_content %}
{% endblock page_content %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

projects/templates/project_detail.html
{% extends "base.html" %}
{% load projects_extras %}
{% load static %}

{% block page_content %}
<h1>{{ project.title }}</h1>
<div class="row">
    <div class="col-md-8">
        <img src="{% static project.image %}" alt="" width="100%">
    </div>
    <div class="col-md-4">
        <h5>About the project:</h5>
        <p>{{ project.description }}</p>
        <br>
        <h5>Technology used:</h5>
        <p>{{ project.technology }}</p>
        <a href = "{% url 'todo_list:main_page' %}">Go to project</a>
    </div>
</div>
{% endblock %}

projects/templates/project_index.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}
<h1>Projects</h1>
<div class="row">
{% for project in projects %}
    <div class="col-md-4">
        <div class="card mb-2">
            <img class="card-img-top" src="{% static project.image %}">
            <div class="card-body">
                <h5 class="card-title">{{ project.title }}</h5>
                <p class="card-text">{{ project.description }}</p>
                <a href="{% url 'projects:project_detail' project.pk %}" class="btn btn-primary">
                    Read More
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

todo_list/templates/base_todo_list.html
{% extends "base.html" %}

{% block navbar %}
<nav class = "navbar navbar-expand-lg navbar-dark bg-primary">
    <a class = "navbar-brand" href = "{% url 'todo_list:main_page' %}">Home</a>
</nav>
{% endblock navbar %}

{% block page_content %}
{% endblock page_content %}

todo_list/templates/main_page.html
{% extends "base_todo_list.html"%}
{% block page_content %}
<div class="col-md-8 offset-md-2">
    <h3>Your To-Do List</h3>
    {% if tasks %}
        <table class = "table">
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Title
                </th>
                <th>
                    Due
                </th> 
                <th>
                </th>
                <th>
                </th>                 
            </tr>

        {% for task in tasks %}
            <tr>
                <td>
                    {{ forloop.counter }} 
                </td>
                <td>
                    {{ task.title }}
                </td>
                <td>
                    {{ task.end_date }}
                </td>
                <td>
                    <a href = "{% url 'todo_list:task_details' task.pk %}" class = "btn btn-primary">Details/Edit</a>
                </td>
                <td>
                    <form action = "{% url 'todo_list:delete_task' task.pk %}" method = "POST">
                        {% csrf_token %}
                        <button type = "submit" class = "btn btn-primary">Delete</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
        </table>
    {% else %}
    <h3>No tasks to display</h3>
    {% endif %}
    <h3>Insert New Task</h3>
    <form method = "POST">
        {% csrf_token %}
        {{ form }}
        <button type = "submit">Submit</button>
    </form>
</div>
{% endblock page_content %}

todo_list/templates/task_details.html
{% extends "base_todo_list.html" %}

{% block page_content %}
<div class = "col-md-8 offset-md-2">
    <h3>Edit Task</h3>
    <form method = "POST">
        {% csrf_token %}
        {{ form }}
        <button type = "submit">Apply Changes</button>
    </form>
</div>
{% endblock page_content %}